version: 2.1

orbs:
  architect: giantswarm/architect@2.11.0

workflows:
  build:
    jobs:
      - architect/push-to-app-catalog:
          context: "architect"
          name: push-argo-events-to-app-catalog
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "argo-events"
          requires:
            - push-argo-events-to-quay
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: push-argo-events-to-shared-app-collection
          context: architect
          app_name: "argo-events"
          app_namespace: "giantswarm"
          app_collection_repo: "shared-app-collection"
          requires:
            - push-argo-events-to-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: push-argo-events-to-aws-app-collection
          context: architect
          app_name: "argo-events"
          app_namespace: "giantswarm"
          app_collection_repo: "aws-app-collection"
          requires:
            - push-argo-events-to-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: push-argo-events-to-azure-app-collection
          context: architect
          app_name: "argo-events"
          app_namespace: "giantswarm"
          app_collection_repo: "azure-app-collection"
          requires:
            - push-argo-events-to-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: push-argo-events-to-kvm-app-collection
          context: architect
          app_name: "argo-events"
          app_namespace: "giantswarm"
          app_collection_repo: "kvm-app-collection"
          requires:
            - push-argo-events-to-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: push-argo-events-to-vmware-app-collection
          context: architect
          app_name: "argo-events"
          app_namespace: "giantswarm"
          app_collection_repo: "vmware-app-collection"
          requires:
            - push-argo-events-to-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
